@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoiMTQ0NWM2ZDktNzg1OC00ZWNjLTlmN2YtMGU3OGU0MzhlNjkxIiwiaWF0IjoxNzY5MzEwMjE2LCJleHAiOjE3NjkzMTM4MTZ9.vCofNRLqsz4XOWUrpoomIBXLhHqmPSZgSHidN66TIJg

# ========================================================
#                  FINANÇAS (tb_finances)
# ========================================================

###
# Criar novo lançamento
POST {{baseUrl}}/api/finances/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "amount": 350.00,
    "receipt_date": "2026-02-25 19:30:00",
    "type": "offering",
    "payment_method": "pix",
    "id_member": "e3a7d35b-0971-4465-adff-e1d09cf766c8"
}

###
# Listar todos
GET {{baseUrl}}/api/finances/get-all
Authorization: Bearer {{token}}

###
# Buscar por ID
GET {{baseUrl}}/api/finances/get/77fa9560-1a5b-43af-a7de-a87f061a6484
Authorization: Bearer {{token}}

###
# Atualizar
PUT {{baseUrl}}/api/finances/update/77fa9560-1a5b-43af-a7de-a87f061a6484
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "amount": 450.00,
    "payment_method": "credit_card"
}

###
# Deletar (soft)
DELETE {{baseUrl}}/api/finances/delete/79179186-55d3-458b-8297-d9ce9d40e2cf
Authorization: Bearer {{token}}

###
# Ativar
PATCH {{baseUrl}}/api/finances/activate/79179186-55d3-458b-8297-d9ce9d40e2cf
Authorization: Bearer {{token}}

###
# Deletar permanentemente (hard)
DELETE {{baseUrl}}/api/finances/delete/79179186-55d3-458b-8297-d9ce9d40e2cf/hard
Authorization: Bearer {{token}}
