@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoiMTQ0NWM2ZDktNzg1OC00ZWNjLTlmN2YtMGU3OGU0MzhlNjkxIiwiaWF0IjoxNzY5MzEwMjE2LCJleHAiOjE3NjkzMTM4MTZ9.vCofNRLqsz4XOWUrpoomIBXLhHqmPSZgSHidN66TIJg

# ========================================================
#                MINISTÉRIOS (tb_ministries)
# ========================================================

###
# Criar novo ministério
POST {{baseUrl}}/api/ministries/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Ministério teste",
    "description": "Ministério teste",
    "id_member": "f038232a-ed9c-4725-b8c7-0d23c2f95421"
}

###
# Listar todos
GET {{baseUrl}}/api/ministries/get-all

###
# Buscar por ID
GET {{baseUrl}}/api/ministries/get/444e1e61-897f-4cda-8949-2eeaa80553cc

###
# Atualizar
PUT {{baseUrl}}/api/ministries/update/444e1e61-897f-4cda-8949-2eeaa80553cc
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Ministério de EBD",
    "description": "Responsável pela educação bíblica dos membros"
}

###
# Deletar (soft)
DELETE {{baseUrl}}/api/ministries/delete/444e1e61-897f-4cda-8949-2eeaa80553cc
Authorization: Bearer {{token}}

###
# Ativar
PATCH {{baseUrl}}/api/ministries/activate/444e1e61-897f-4cda-8949-2eeaa80553cc
Authorization: Bearer {{token}}

###
# Deletar permanentemente (hard)
DELETE {{baseUrl}}/api/ministries/delete/b6b5bd1a-a720-4cd3-92d9-5e84ec3da6cf/hard
Authorization: Bearer {{token}}
